require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'docs/**/*'
    - 'tmp/**/*'
    - '*.gemspec'
    - 'Gemfile'
    - 'Rakefile'

# Layout and formatting
Layout/LineLength:
  Max: 120
  AllowedPatterns: ['\A\s*#']

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Metrics
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Rakefile'

Metrics/MethodLength:
  Max: 20
  CountAsOne: ['array', 'hash', 'heredoc']

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 8

# Style
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/EmptyMethod:
  EnforcedStyle: expanded

# Naming
Naming/PredicateName:
  ForbiddenPrefixes:
    - is_

Naming/AccessorMethodName:
  Enabled: false

# RSpec specific cops
RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Enabled: true

RSpec/FilePath:
  Enabled: true

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for

RSpec/DescribedClass:
  Enabled: true

# Security
Security/Eval:
  Enabled: true

Security/Open:
  Enabled: true

Security/YAMLLoad:
  Enabled: true

# Bundler
Bundler/OrderedGems:
  Enabled: true

# Gemspec
Gemspec/OrderedDependencies:
  Enabled: true

Gemspec/RequiredRubyVersion:
  Enabled: true