name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            chore
            ci
            build
          requireScope: false
          disallowScopes: |
            release
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.

  changelog-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changelog update
        run: |
          # Skip changelog check for certain PR types
          pr_title="${{ github.event.pull_request.title }}"
          if [[ $pr_title =~ ^(chore|ci|docs|style|test): ]]; then
            echo "Skipping changelog check for $pr_title"
            exit 0
          fi

          # Check if CHANGELOG.md was modified
          if git diff --name-only origin/master...HEAD | grep -q "CHANGELOG.md"; then
            echo "✅ CHANGELOG.md was updated"
          else
            echo "❌ Please update CHANGELOG.md with your changes"
            echo "Add an entry under the ## [Unreleased] section"
            exit 1
          fi

  gem-build-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Validate gemspec
        run: |
          bundle exec gem build attio.gemspec --strict
          echo "✅ Gemspec is valid"

      - name: Check gem installation
        run: |
          gem_file=$(ls attio-*.gem | head -1)
          gem install "$gem_file"
          ruby -c -e "require 'attio'"
          echo "✅ Gem can be required successfully"

  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Run Danger
        run: bundle exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Run security checks
        run: |
          bundle exec bundler-audit check --update
          echo "✅ No known security vulnerabilities found"

  pr-size-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check PR size
        run: |
          files_changed=$(git diff --name-only origin/main...HEAD | wc -l)
          lines_changed=$(git diff --shortstat origin/main...HEAD | awk '{print $4+$6}' || echo "0")
          
          echo "Files changed: $files_changed"
          echo "Lines changed: $lines_changed"
          
          if [ "$files_changed" -gt 50 ]; then
            echo "⚠️  This PR changes $files_changed files. Consider breaking it into smaller PRs."
          fi
          
          if [ "$lines_changed" -gt 1000 ]; then
            echo "⚠️  This PR changes $lines_changed lines. Consider breaking it into smaller PRs."
          fi
          
          # Don't fail the check, just provide warnings